### ISSUE TITLE
Steam Booster Pack Contribution

### ISSUE THREAD

**Issue by marcos-tomaz** [16ROCK/Steam-User-Manager#1]
Hello buddy, 
Sorry to bother you and leave a message in that repo, but I didn't find any other way to contact you.
Regarding the extension [Steam Booster Pack Create Helper](https://chrome.google.com/webstore/detail/steam-booster-packs-creat/knhicbficbafeombbgjfenfjfngmnann) there is some way I can contribute to the original code?
I use this extension a lot and I've made some enhancements that I would like to share.

Anyway, thank you!

**Comment by 16ROCK** [comment]
> Hello buddy, Sorry to bother you and leave a message in that repo, but I didn't find any other way to contact you. Regarding the extension [Steam Booster Pack Create Helper](https://chrome.google.com/webstore/detail/steam-booster-packs-creat/knhicbficbafeombbgjfenfjfngmnann) there is some way I can contribute to the original code? I use this extension a lot and I've made some enhancements that I would like to share.
> 
> Anyway, thank you!

Hello, yes
My telegram: http://t.me/erheis
